name: Test Workflow

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  push:
    branches:
      - '**'  # Trigger on pushes to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out the code

    - name: Set up Python
      uses: actions/setup-python@v2  # Sets up the specified Python version
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installs dependencies

    - name: Run Unit Tests
      run: |
        pytest --junitxml=results.xml  # Executes unit tests and saves results

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results  # Uploads test results for review
        path: results.xml
